safe: false
excerpt_separator: "\n\n\n"
sitemapurl: "https:\\wangkun19930608.github.io"


  
  
  
# Site settings
#title: WK Blog
#SEOTitle: 王坤的博客 | Wangkun Blog
#header-img: img/home-bg.jpg
#email: wangkun19930608@gmail.com
#description: "关于计算机 | 王坤，Web & Mobile Lover，Software Engineer，UX Designer | 这里是 王坤 的个人博客，与你一起发现更大的世界。"
#keyword: "WANGKUN, 王坤,  博客, 个人网站, 互联网, Web, JavaScript, 前端, 设计"
url: "https:\\wangkun19930608.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'


# SNS settings
#RSS: false
#weibo_username:     wangkun
#zhihu_username:     wangkun
#github_username:    wangkun
#twitter_username:   wangkun
#facebook_username:  wangkun
# linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
#exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
#anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# gems: [jekyll-paginate]
#   Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly. 20190613
# If you are using Jekyll < 3.5.0 use the gems key instead of plugins. 
# - jekyll-seo-tag   
# Search engine optimization for GitHub Pages - GitHub Help
#https://help.github.com/en/articles/search-engine-optimization-for-github-pages
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
  - jekyll-toc
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-include-cache
  


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
#disqus_username: wk

# Netease setttings
#netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: wangkun19930608.github.io



# Sidebar settings
#sidebar: true                           # whether or not using Sidebar.
#sidebar-about-description: "写写代码，做做设计，<br>离开世界之前，一切都是过程"
#sidebar-avatar: /img/home-bg.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
#featured-tags: true                     # whether or not using Feature-Tags
#featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
#chrome-tab-theme-color: "#000000"
#service-worker: true



#Friends
friends: [
   {
       title: "Su",
       href: "http://su.gallery/"
   },{
       title: "乱序",
       href: "http://mida.re/"
   },{
       title: "前端外刊评论",
       href: "http://qianduan.guru/"
   },{
       title: "天镶的博客",
       href: "http://lingyu.wang/"
   },{
       title: "Luke 的自留地",
       href: "http://hmqk1995.github.io"
   },{
       title: "Ebn's Blog",
       href: "http://ebnbin.com/"
   },{
       title: "SmdCn's Blog",
       href: "http://blog.smdcn.net"
   },{
       title: "解旻的博客",
       href: "http://xieminis.me/"
   },{
       title: "DHong Say",
       href: "http://dhong.co"
   },{
       title: "尹峰以为",
       href: "http://ingf.github.io/"
   },{
       title: "前端神盾局",
       href: "http://wepiaofei.github.io/blog/"
   },{
       title: "潇湘夜雨",
       href: "https://minixalpha.github.io/"
   }
]


theme: jekyll-theme-cayman